---
spring:
  profiles: dev
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://172.18.4.44:3306/orderDB?characterEncoding=utf-8&useSSL=false


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081

girl:
  name: yyy
  age: 18
